# Generated by Django 3.1.5 on 2021-02-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myupdate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myupdate',
            old_name='compete',
            new_name='complete',
        ),
    ]
